Error during layout fix
Caused by: java.lang.NoSuchMethodError: 'void fleet.compose.theme.components.IconKt.Icon-USBMPiE$default(noria.NoriaContext, noria.model.ThemeKey, long, androidx.compose.ui.Modifier, java.util.Map, java.lang.Float, int, java.lang.Object)'
	at fleet.gradle.daemons.frontend/fleet.gradle.daemons.frontend.DaemonsViewKt$renderDaemonsView$3$listModel$2$2$1.invoke(DaemonsView.kt:161)
	at fleet.gradle.daemons.frontend/fleet.gradle.daemons.frontend.DaemonsViewKt$renderDaemonsView$3$listModel$2$2$1.invoke(DaemonsView.kt:160)